from functools import partial
from typing import Any, Callable, TypeVar

from aiogram.types import (
    Animation,
    Audio,
    Location,
    PhotoSize,
    RichBlock,
    RichBlockAnchor,
    RichBlockAnimation,
    RichBlockAudio,
    RichBlockBlockQuotation,
    RichBlockCaption,
    RichBlockCollage,
    RichBlockDetails,
    RichBlockDivider,
    RichBlockFooter,
    RichBlockList,
    RichBlockListItem,
    RichBlockMap,
    RichBlockMathematicalExpression,
    RichBlockParagraph,
    RichBlockPhoto,
    RichBlockPreformatted,
    RichBlockPullQuotation,
    RichBlockSectionHeading,
    RichBlockSlideshow,
    RichBlockTable,
    RichBlockTableCell,
    RichBlockThinking,
    RichBlockUnion,
    RichBlockVideo,
    RichBlockVoiceNote,
    RichMessage,
    RichText,
    RichTextAnchor,
    RichTextAnchorLink,
    RichTextBankCardNumber,
    RichTextBold,
    RichTextBotCommand,
    RichTextCashtag,
    RichTextCode,
    RichTextCustomEmoji,
    RichTextDateTime,
    RichTextEmailAddress,
    RichTextHashtag,
    RichTextItalic,
    RichTextMarked,
    RichTextMathematicalExpression,
    RichTextMention,
    RichTextPhoneNumber,
    RichTextReference,
    RichTextReferenceLink,
    RichTextSpoiler,
    RichTextStrikethrough,
    RichTextSubscript,
    RichTextSuperscript,
    RichTextTextMention,
    RichTextUnderline,
    RichTextUnion,
    RichTextUrl,
    Video,
    Voice,
)

BLOCKS = [
    RichBlockParagraph(
        type="paragraph",
        text=[
            RichTextAnchor(
                type="anchor",
                name="chapter-0",
            ),
            " ",
            RichTextBold(type="bold", text="bold text"),
            ", ",
            RichTextBold(type="bold", text="bold text"),
            " ",
            RichTextItalic(type="italic", text="italic text"),
            ", ",
            RichTextItalic(type="italic", text="italic text"),
            " ",
            RichTextUnderline(type="underline", text="underlined text"),
            ", ",
            RichTextUnderline(type="underline", text="underlined text"),
            " ",
            RichTextStrikethrough(type="strikethrough", text="strikethrough text"),
            ", ",
            RichTextStrikethrough(type="strikethrough", text="strikethrough text"),
            ", ",
            RichTextStrikethrough(type="strikethrough", text="strikethrough text"),
            " ",
            RichTextCode(type="code", text="inline fixed-width code"),
            " ",
            RichTextMarked(type="marked", text="marked text"),
            " ",
            RichTextSubscript(type="subscript", text="subscript text"),
            " ",
            RichTextSuperscript(type="superscript", text="superscript text"),
            " ",
            RichTextSpoiler(type="spoiler", text="spoiler"),
            " ",
            RichTextReferenceLink(
                type="reference_link", text="Reference", reference_name="note-1"
            ),
            " ",
            RichTextUrl(type="url", text="inline URL", url="https://t.me/"),
            " ",
            RichTextEmailAddress(
                type="email_address", text="inline e-mail", email_address="user@example.com"
            ),
            " ",
            RichTextPhoneNumber(
                type="phone_number", text="inline phone number", phone_number="+123456789"
            ),
            " inline mention of a user ",
            RichTextAnchorLink(
                type="anchor_link", text="in-document link", anchor_name="chapter-1"
            ),
            " ",
            RichTextAnchor(type="anchor", name="chapter-1"),
            " ",
            RichTextReference(type="reference", text="Referenced text", name="note-1"),
            " ",
            RichTextCustomEmoji(
                type="custom_emoji", custom_emoji_id="5368324170671202286", alternative_text="👍"
            ),
            " ",
            RichTextCustomEmoji(
                type="custom_emoji", custom_emoji_id="5368324170671202286", alternative_text="👍"
            ),
            " ",
            RichTextDateTime(
                type="date_time",
                text="22:45 tomorrow",
                unix_time=1647531900,
                date_time_format="wDT",
            ),
            " ",
            RichTextMathematicalExpression(type="mathematical_expression", expression="x^2 + y^2"),
            " ",
            RichTextHashtag(type="hashtag", text="#hashtag", hashtag="hashtag"),
            " ",
            RichTextCashtag(type="cashtag", text="$USD", cashtag="USD"),
            " ",
            RichTextPhoneNumber(
                type="phone_number", text="+12345678901", phone_number="+12345678901"
            ),
            ", card: 4242 4242 4242 4242, ",
            RichTextUrl(type="url", text="https://t.me", url="https://t.me"),
            " ",
            RichTextUrl(type="url", text="t.me", url="t.me"),
            " ",
            RichTextEmailAddress(type="email_address", text="a@t.me", email_address="a@t.me"),
            " ",
            RichTextBotCommand(type="bot_command", text="/command", bot_command="command"),
            " ",
            RichTextMention(type="mention", text="@username", username="username"),
            " all the text above was on the same line",
        ],
    ),
    RichBlockSectionHeading(type="heading", text="Heading 1", size=1),
    RichBlockSectionHeading(type="heading", text="Heading 2", size=2),
    RichBlockSectionHeading(type="heading", text="Heading 3", size=3),
    RichBlockSectionHeading(type="heading", text="Heading 4", size=4),
    RichBlockSectionHeading(type="heading", text="Heading 5", size=5),
    RichBlockSectionHeading(type="heading", text="Heading 6", size=6),
    RichBlockAnchor(type="anchor", name="chapter-2"),
    RichBlockParagraph(type="paragraph", text="Paragraph text"),
    RichBlockPreformatted(type="pre", text="pre-formatted fixed-width code block", language=None),
    RichBlockPreformatted(
        type="pre",
        text="  print('pre-formatted fixed-width code block written in the Python programming language')",
        language="python",
    ),
    RichBlockFooter(type="footer", text="Footer text"),
    RichBlockDivider(type="divider"),
    RichBlockList(
        type="list",
        items=[
            RichBlockListItem(
                label="•",
                blocks=[RichBlockParagraph(type="paragraph", text="unordered list item")],
                has_checkbox=None,
                is_checked=None,
                value=None,
                type=None,
            )
        ],
    ),
    RichBlockList(
        type="list",
        items=[
            RichBlockListItem(
                label="1.",
                blocks=[RichBlockParagraph(type="paragraph", text="ordered list item")],
                has_checkbox=None,
                is_checked=None,
                value=1,
                type="1",
            )
        ],
    ),
    RichBlockList(
        type="list",
        items=[
            RichBlockListItem(
                label="c.",
                blocks=[RichBlockParagraph(type="paragraph", text="ordered list item")],
                has_checkbox=None,
                is_checked=None,
                value=3,
                type="a",
            )
        ],
    ),
    RichBlockList(
        type="list",
        items=[
            RichBlockListItem(
                label="vii.",
                blocks=[
                    RichBlockParagraph(
                        type="paragraph", text="ordered list item with explicit number"
                    )
                ],
                has_checkbox=None,
                is_checked=None,
                value=7,
                type="i",
            )
        ],
    ),
    RichBlockList(
        type="list",
        items=[
            RichBlockListItem(
                label="•",
                blocks=[RichBlockParagraph(type="paragraph", text="Checked checkbox")],
                has_checkbox=True,
                is_checked=True,
                value=None,
                type=None,
            ),
            RichBlockListItem(
                label="•",
                blocks=[RichBlockParagraph(type="paragraph", text="Unchecked checkbox")],
                has_checkbox=True,
                is_checked=None,
                value=None,
                type=None,
            ),
        ],
    ),
    RichBlockBlockQuotation(
        type="blockquote",
        blocks=[
            RichBlockParagraph(
                type="paragraph",
                text="Block quotation started\nBlock quotation continued\nThe last line of the block quotation",
            )
        ],
        credit="The Author",
    ),
    RichBlockPullQuotation(type="pullquote", text="Pull quote", credit="The Author"),
    RichBlockPhoto(
        type="photo",
        photo=[
            PhotoSize(
                file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADcwADPAQ",
                file_unique_id="AQAD4A1rG4xifVF4",
                width=90,
                height=51,
                file_size=1081,
            ),
            PhotoSize(
                file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADbQADPAQ",
                file_unique_id="AQAD4A1rG4xifVFy",
                width=320,
                height=180,
                file_size=13004,
            ),
            PhotoSize(
                file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADeAADPAQ",
                file_unique_id="AQAD4A1rG4xifVF9",
                width=800,
                height=450,
                file_size=55714,
            ),
            PhotoSize(
                file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADeQADPAQ",
                file_unique_id="AQAD4A1rG4xifVF-",
                width=1280,
                height=720,
                file_size=118930,
            ),
            PhotoSize(
                file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADdwADPAQ",
                file_unique_id="AQAD4A1rG4xifVF8",
                width=1920,
                height=1080,
                file_size=202060,
            ),
        ],
        has_spoiler=None,
        caption=None,
    ),
    RichBlockVideo(
        type="video",
        video=Video(
            file_id="BAACAgQAAxUAAWov83F5bXcfGrb9G7QqJs5umyDXAALCCgACjvJtUYeBk5lHxyKPPAQ",
            file_unique_id="AgADwgoAAo7ybVE",
            width=1280,
            height=720,
            duration=44,
            thumbnail=PhotoSize(
                file_id="AAMCBAADFQABai_zcXltdx8atv0btComzm6bINcAAsIKAAKO8m1Rh4GTmUfHIo8BAAdtAAM8BA",
                file_unique_id="AQADwgoAAo7ybVFy",
                width=320,
                height=180,
                file_size=8374,
            ),
            cover=None,
            start_timestamp=None,
            qualities=None,
            file_name="video.mp4",
            mime_type="video/mp4",
            file_size=7271495,
            thumb={
                "file_id": "AAMCBAADFQABai_zcXltdx8atv0btComzm6bINcAAsIKAAKO8m1Rh4GTmUfHIo8BAAdtAAM8BA",
                "file_unique_id": "AQADwgoAAo7ybVFy",
                "file_size": 8374,
                "width": 320,
                "height": 180,
            },
        ),
        has_spoiler=None,
        caption=None,
    ),
    RichBlockAudio(
        type="audio",
        audio=Audio(
            file_id="CQACAgQAAxUAAWov83GB0bnqjANy878vlC8rv7IAA-4KAAJ_W2xRWnK-nYCvhQs8BA",
            file_unique_id="AgAD7goAAn9bbFE",
            duration=43,
            performer=None,
            title=None,
            file_name="audio.mp3",
            mime_type="audio/mpeg",
            file_size=689133,
            thumbnail=None,
        ),
        caption=None,
    ),
    RichBlockVoiceNote(
        type="voice_note",
        voice_note=Voice(
            file_id="AwACAgQAAxUAAWov83FGZNZdCs16cM3-oju_cAgjAAKOCgACpBZsUYutvj8QjxEDPAQ",
            file_unique_id="AgADjgoAAqQWbFE",
            duration=43,
            mime_type="audio/ogg",
            file_size=554181,
        ),
        caption=None,
    ),
    RichBlockAnimation(
        type="animation",
        animation=Animation(
            file_id="CgACAgQAAxUAAWov83FbhQJGGGo1gjGPT79EBglWAAJlCwACwjFsUZ3U7okfR-s-PAQ",
            file_unique_id="AgADZQsAAsIxbFE",
            width=320,
            height=180,
            duration=5,
            thumbnail=PhotoSize(
                file_id="AAMCBAADFQABai_zcVuFAkYYajWCMY9Pv0QGCVYAAmULAALCMWxRndTuiR9H6z4BAAdtAAM8BA",
                file_unique_id="AQADZQsAAsIxbFFy",
                width=320,
                height=180,
                file_size=9656,
            ),
            file_name="animation.gif.mp4",
            mime_type="video/mp4",
            file_size=100854,
            thumb={
                "file_id": "AAMCBAADFQABai_zcVuFAkYYajWCMY9Pv0QGCVYAAmULAALCMWxRndTuiR9H6z4BAAdtAAM8BA",
                "file_unique_id": "AQADZQsAAsIxbFFy",
                "file_size": 9656,
                "width": 320,
                "height": 180,
            },
        ),
        has_spoiler=None,
        caption=None,
        need_autoplay=True,
    ),
    RichBlockPhoto(
        type="photo",
        photo=[
            PhotoSize(
                file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADcwADPAQ",
                file_unique_id="AQAD4A1rG4xifVF4",
                width=90,
                height=51,
                file_size=1081,
            ),
            PhotoSize(
                file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADbQADPAQ",
                file_unique_id="AQAD4A1rG4xifVFy",
                width=320,
                height=180,
                file_size=13004,
            ),
            PhotoSize(
                file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADeAADPAQ",
                file_unique_id="AQAD4A1rG4xifVF9",
                width=800,
                height=450,
                file_size=55714,
            ),
            PhotoSize(
                file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADeQADPAQ",
                file_unique_id="AQAD4A1rG4xifVF-",
                width=1280,
                height=720,
                file_size=118930,
            ),
            PhotoSize(
                file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADdwADPAQ",
                file_unique_id="AQAD4A1rG4xifVF8",
                width=1920,
                height=1080,
                file_size=202060,
            ),
        ],
        has_spoiler=True,
        caption=RichBlockCaption(text="Photo caption", credit="Photo credit"),
    ),
    RichBlockVideo(
        type="video",
        video=Video(
            file_id="BAACAgQAAxUAAWov83F5bXcfGrb9G7QqJs5umyDXAALCCgACjvJtUYeBk5lHxyKPPAQ",
            file_unique_id="AgADwgoAAo7ybVE",
            width=1280,
            height=720,
            duration=44,
            thumbnail=PhotoSize(
                file_id="AAMCBAADFQABai_zcXltdx8atv0btComzm6bINcAAsIKAAKO8m1Rh4GTmUfHIo8BAAdtAAM8BA",
                file_unique_id="AQADwgoAAo7ybVFy",
                width=320,
                height=180,
                file_size=8374,
            ),
            cover=None,
            start_timestamp=None,
            qualities=None,
            file_name="video.mp4",
            mime_type="video/mp4",
            file_size=7271495,
            thumb={
                "file_id": "AAMCBAADFQABai_zcXltdx8atv0btComzm6bINcAAsIKAAKO8m1Rh4GTmUfHIo8BAAdtAAM8BA",
                "file_unique_id": "AQADwgoAAo7ybVFy",
                "file_size": 8374,
                "width": 320,
                "height": 180,
            },
        ),
        has_spoiler=True,
        caption=RichBlockCaption(text="Video caption", credit=None),
    ),
    RichBlockAudio(
        type="audio",
        audio=Audio(
            file_id="CQACAgQAAxUAAWov83GB0bnqjANy878vlC8rv7IAA-4KAAJ_W2xRWnK-nYCvhQs8BA",
            file_unique_id="AgAD7goAAn9bbFE",
            duration=43,
            performer=None,
            title=None,
            file_name="audio.mp3",
            mime_type="audio/mpeg",
            file_size=689133,
            thumbnail=None,
        ),
        caption=RichBlockCaption(text="Audio caption", credit=None),
    ),
    RichBlockVoiceNote(
        type="voice_note",
        voice_note=Voice(
            file_id="AwACAgQAAxUAAWov83FGZNZdCs16cM3-oju_cAgjAAKOCgACpBZsUYutvj8QjxEDPAQ",
            file_unique_id="AgADjgoAAqQWbFE",
            duration=43,
            mime_type="audio/ogg",
            file_size=554181,
        ),
        caption=RichBlockCaption(text="Voice note caption", credit=None),
    ),
    RichBlockAnimation(
        type="animation",
        animation=Animation(
            file_id="CgACAgQAAxUAAWov83FbhQJGGGo1gjGPT79EBglWAAJlCwACwjFsUZ3U7okfR-s-PAQ",
            file_unique_id="AgADZQsAAsIxbFE",
            width=320,
            height=180,
            duration=5,
            thumbnail=PhotoSize(
                file_id="AAMCBAADFQABai_zcVuFAkYYajWCMY9Pv0QGCVYAAmULAALCMWxRndTuiR9H6z4BAAdtAAM8BA",
                file_unique_id="AQADZQsAAsIxbFFy",
                width=320,
                height=180,
                file_size=9656,
            ),
            file_name="animation.gif.mp4",
            mime_type="video/mp4",
            file_size=100854,
            thumb={
                "file_id": "AAMCBAADFQABai_zcVuFAkYYajWCMY9Pv0QGCVYAAmULAALCMWxRndTuiR9H6z4BAAdtAAM8BA",
                "file_unique_id": "AQADZQsAAsIxbFFy",
                "file_size": 9656,
                "width": 320,
                "height": 180,
            },
        ),
        has_spoiler=True,
        caption=RichBlockCaption(text="Animation caption", credit=None),
        need_autoplay=True,
    ),
    RichBlockMap(
        type="map",
        location=Location(
            latitude=41.900006,
            longitude=12.500002,
            horizontal_accuracy=None,
            live_period=None,
            heading=None,
            proximity_alert_radius=None,
        ),
        zoom=14,
        width=400,
        height=200,
        caption=None,
    ),
    RichBlockMap(
        type="map",
        location=Location(
            latitude=41.900006,
            longitude=12.500002,
            horizontal_accuracy=None,
            live_period=None,
            heading=None,
            proximity_alert_radius=None,
        ),
        zoom=14,
        width=400,
        height=200,
        caption=RichBlockCaption(text="Map caption", credit=None),
    ),
    RichBlockCollage(
        type="collage",
        blocks=[
            RichBlockPhoto(
                type="photo",
                photo=[
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADcwADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF4",
                        width=90,
                        height=51,
                        file_size=1081,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADbQADPAQ",
                        file_unique_id="AQAD4A1rG4xifVFy",
                        width=320,
                        height=180,
                        file_size=13004,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADeAADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF9",
                        width=800,
                        height=450,
                        file_size=55714,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADeQADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF-",
                        width=1280,
                        height=720,
                        file_size=118930,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADdwADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF8",
                        width=1920,
                        height=1080,
                        file_size=202060,
                    ),
                ],
                has_spoiler=None,
                caption=None,
            ),
            RichBlockVideo(
                type="video",
                video=Video(
                    file_id="BAACAgQAAxUAAWov83F5bXcfGrb9G7QqJs5umyDXAALCCgACjvJtUYeBk5lHxyKPPAQ",
                    file_unique_id="AgADwgoAAo7ybVE",
                    width=1280,
                    height=720,
                    duration=44,
                    thumbnail=PhotoSize(
                        file_id="AAMCBAADFQABai_zcXltdx8atv0btComzm6bINcAAsIKAAKO8m1Rh4GTmUfHIo8BAAdtAAM8BA",
                        file_unique_id="AQADwgoAAo7ybVFy",
                        width=320,
                        height=180,
                        file_size=8374,
                    ),
                    cover=None,
                    start_timestamp=None,
                    qualities=None,
                    file_name="video.mp4",
                    mime_type="video/mp4",
                    file_size=7271495,
                    thumb={
                        "file_id": "AAMCBAADFQABai_zcXltdx8atv0btComzm6bINcAAsIKAAKO8m1Rh4GTmUfHIo8BAAdtAAM8BA",
                        "file_unique_id": "AQADwgoAAo7ybVFy",
                        "file_size": 8374,
                        "width": 320,
                        "height": 180,
                    },
                ),
                has_spoiler=None,
                caption=None,
            ),
        ],
        caption=None,
    ),
    RichBlockCollage(
        type="collage",
        blocks=[
            RichBlockVideo(
                type="video",
                video=Video(
                    file_id="BAACAgQAAxUAAWov83F5bXcfGrb9G7QqJs5umyDXAALCCgACjvJtUYeBk5lHxyKPPAQ",
                    file_unique_id="AgADwgoAAo7ybVE",
                    width=1280,
                    height=720,
                    duration=44,
                    thumbnail=PhotoSize(
                        file_id="AAMCBAADFQABai_zcXltdx8atv0btComzm6bINcAAsIKAAKO8m1Rh4GTmUfHIo8BAAdtAAM8BA",
                        file_unique_id="AQADwgoAAo7ybVFy",
                        width=320,
                        height=180,
                        file_size=8374,
                    ),
                    cover=None,
                    start_timestamp=None,
                    qualities=None,
                    file_name="video.mp4",
                    mime_type="video/mp4",
                    file_size=7271495,
                    thumb={
                        "file_id": "AAMCBAADFQABai_zcXltdx8atv0btComzm6bINcAAsIKAAKO8m1Rh4GTmUfHIo8BAAdtAAM8BA",
                        "file_unique_id": "AQADwgoAAo7ybVFy",
                        "file_size": 8374,
                        "width": 320,
                        "height": 180,
                    },
                ),
                has_spoiler=None,
                caption=None,
            ),
            RichBlockPhoto(
                type="photo",
                photo=[
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADcwADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF4",
                        width=90,
                        height=51,
                        file_size=1081,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADbQADPAQ",
                        file_unique_id="AQAD4A1rG4xifVFy",
                        width=320,
                        height=180,
                        file_size=13004,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADeAADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF9",
                        width=800,
                        height=450,
                        file_size=55714,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADeQADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF-",
                        width=1280,
                        height=720,
                        file_size=118930,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADdwADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF8",
                        width=1920,
                        height=1080,
                        file_size=202060,
                    ),
                ],
                has_spoiler=None,
                caption=None,
            ),
        ],
        caption=RichBlockCaption(text="Collage caption", credit=None),
    ),
    RichBlockSlideshow(
        type="slideshow",
        blocks=[
            RichBlockPhoto(
                type="photo",
                photo=[
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADcwADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF4",
                        width=90,
                        height=51,
                        file_size=1081,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADbQADPAQ",
                        file_unique_id="AQAD4A1rG4xifVFy",
                        width=320,
                        height=180,
                        file_size=13004,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADeAADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF9",
                        width=800,
                        height=450,
                        file_size=55714,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADeQADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF-",
                        width=1280,
                        height=720,
                        file_size=118930,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADdwADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF8",
                        width=1920,
                        height=1080,
                        file_size=202060,
                    ),
                ],
                has_spoiler=None,
                caption=None,
            ),
            RichBlockVideo(
                type="video",
                video=Video(
                    file_id="BAACAgQAAxUAAWov83F5bXcfGrb9G7QqJs5umyDXAALCCgACjvJtUYeBk5lHxyKPPAQ",
                    file_unique_id="AgADwgoAAo7ybVE",
                    width=1280,
                    height=720,
                    duration=44,
                    thumbnail=PhotoSize(
                        file_id="AAMCBAADFQABai_zcXltdx8atv0btComzm6bINcAAsIKAAKO8m1Rh4GTmUfHIo8BAAdtAAM8BA",
                        file_unique_id="AQADwgoAAo7ybVFy",
                        width=320,
                        height=180,
                        file_size=8374,
                    ),
                    cover=None,
                    start_timestamp=None,
                    qualities=None,
                    file_name="video.mp4",
                    mime_type="video/mp4",
                    file_size=7271495,
                    thumb={
                        "file_id": "AAMCBAADFQABai_zcXltdx8atv0btComzm6bINcAAsIKAAKO8m1Rh4GTmUfHIo8BAAdtAAM8BA",
                        "file_unique_id": "AQADwgoAAo7ybVFy",
                        "file_size": 8374,
                        "width": 320,
                        "height": 180,
                    },
                ),
                has_spoiler=None,
                caption=None,
            ),
        ],
        caption=None,
    ),
    RichBlockSlideshow(
        type="slideshow",
        blocks=[
            RichBlockVideo(
                type="video",
                video=Video(
                    file_id="BAACAgQAAxUAAWov83F5bXcfGrb9G7QqJs5umyDXAALCCgACjvJtUYeBk5lHxyKPPAQ",
                    file_unique_id="AgADwgoAAo7ybVE",
                    width=1280,
                    height=720,
                    duration=44,
                    thumbnail=PhotoSize(
                        file_id="AAMCBAADFQABai_zcXltdx8atv0btComzm6bINcAAsIKAAKO8m1Rh4GTmUfHIo8BAAdtAAM8BA",
                        file_unique_id="AQADwgoAAo7ybVFy",
                        width=320,
                        height=180,
                        file_size=8374,
                    ),
                    cover=None,
                    start_timestamp=None,
                    qualities=None,
                    file_name="video.mp4",
                    mime_type="video/mp4",
                    file_size=7271495,
                    thumb={
                        "file_id": "AAMCBAADFQABai_zcXltdx8atv0btComzm6bINcAAsIKAAKO8m1Rh4GTmUfHIo8BAAdtAAM8BA",
                        "file_unique_id": "AQADwgoAAo7ybVFy",
                        "file_size": 8374,
                        "width": 320,
                        "height": 180,
                    },
                ),
                has_spoiler=None,
                caption=None,
            ),
            RichBlockPhoto(
                type="photo",
                photo=[
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADcwADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF4",
                        width=90,
                        height=51,
                        file_size=1081,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADbQADPAQ",
                        file_unique_id="AQAD4A1rG4xifVFy",
                        width=320,
                        height=180,
                        file_size=13004,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADeAADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF9",
                        width=800,
                        height=450,
                        file_size=55714,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADeQADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF-",
                        width=1280,
                        height=720,
                        file_size=118930,
                    ),
                    PhotoSize(
                        file_id="AgACAgQAAxUAAWov83Gtc9QQID9xhobmfiCExEpgAALgDWsbjGJ9UcxDCGI3F2THAQADAgADdwADPAQ",
                        file_unique_id="AQAD4A1rG4xifVF8",
                        width=1920,
                        height=1080,
                        file_size=202060,
                    ),
                ],
                has_spoiler=None,
                caption=None,
            ),
        ],
        caption=RichBlockCaption(text="Slideshow caption", credit=None),
    ),
    RichBlockTable(
        type="table",
        cells=[
            [
                RichBlockTableCell(
                    align="center",
                    valign="middle",
                    text="Header 1",
                    is_header=True,
                    colspan=None,
                    rowspan=None,
                ),
                RichBlockTableCell(
                    align="center",
                    valign="middle",
                    text="Header 2",
                    is_header=True,
                    colspan=None,
                    rowspan=None,
                ),
            ],
            [
                RichBlockTableCell(
                    align="left",
                    valign="middle",
                    text="Value 1",
                    is_header=None,
                    colspan=None,
                    rowspan=None,
                ),
                RichBlockTableCell(
                    align="left",
                    valign="middle",
                    text="Value 2",
                    is_header=None,
                    colspan=None,
                    rowspan=None,
                ),
            ],
        ],
        is_bordered=None,
        is_striped=None,
        caption=None,
    ),
    RichBlockTable(
        type="table",
        cells=[
            [
                RichBlockTableCell(
                    align="left",
                    valign="middle",
                    text="Value",
                    is_header=None,
                    colspan=2,
                    rowspan=2,
                ),
                RichBlockTableCell(
                    align="center",
                    valign="middle",
                    text="Value2",
                    is_header=None,
                    colspan=None,
                    rowspan=None,
                ),
                RichBlockTableCell(
                    align="right",
                    valign="middle",
                    text="Value3",
                    is_header=None,
                    colspan=None,
                    rowspan=None,
                ),
                RichBlockTableCell(
                    align="left",
                    valign="top",
                    text=None,
                    is_header=None,
                    colspan=None,
                    rowspan=None,
                ),
            ],
            [
                RichBlockTableCell(
                    align="left",
                    valign="top",
                    text="Value4",
                    is_header=None,
                    colspan=None,
                    rowspan=None,
                ),
                RichBlockTableCell(
                    align="left",
                    valign="middle",
                    text="Value5",
                    is_header=None,
                    colspan=None,
                    rowspan=None,
                ),
                RichBlockTableCell(
                    align="left",
                    valign="bottom",
                    text="Value6",
                    is_header=None,
                    colspan=None,
                    rowspan=None,
                ),
            ],
            [
                RichBlockTableCell(
                    align="left",
                    valign="middle",
                    text="Value7",
                    is_header=None,
                    colspan=None,
                    rowspan=None,
                ),
                RichBlockTableCell(
                    align="left", valign="top", text=None, is_header=None, colspan=4, rowspan=None
                ),
            ],
        ],
        is_bordered=True,
        is_striped=True,
        caption="Table caption",
    ),
    RichBlockDetails(
        type="details",
        summary="Title",
        blocks=[RichBlockParagraph(type="paragraph", text="Content")],
        is_open=None,
    ),
    RichBlockDetails(
        type="details",
        summary="Title",
        blocks=[RichBlockParagraph(type="paragraph", text="Content")],
        is_open=True,
    ),
    RichBlockMathematicalExpression(type="mathematical_expression", expression="E = mc^2"),
]


def tag(
    name: str,
    value: str | None = None,
    attrs: dict[str, str] | None = None,
    flags: dict[str, bool] | None = None,
) -> str:
    if value is None:
        value = ""

    prepared_attrs = [name]
    if attrs:
        prepared_attrs.extend([f"{key}={value}" for key, value in attrs.items()])
    if flags:
        prepared_attrs.extend([key for key, value in flags.items() if value])

    return f"<{' '.join(prepared_attrs)}>{value}</{name}>"


def render(
    blocks: list[RichBlock], mappers: dict[type[RichBlock], Callable[[RichBlock], str]]
) -> str:
    r = partial(render, mappers=mappers)
    return "".join(
        mappers.get(type(block), lambda b, _: f"!!{type(b).__name__}!!")(block, r)
        for block in blocks
    )


B = TypeVar("B")
HTML_MAPPER: dict[type[B], Callable[[B, Any], str]] = {
    RichBlockParagraph: lambda block, r: tag("p", r(block.text)),
    RichBlockSectionHeading: lambda block, r: tag(f"h{block.size}", r(block.text)),
    # RichBlockPhoto: lambda block: f"<img src='{block.url}' alt='{block.caption}' />",
    # RichBlockVideo: lambda block: f"<video src='{block.url}' controls></video>",
    # RichBlockAudio: lambda block: f"<audio src='{block.url}' controls></audio>",
    # RichBlockAnimation: lambda block: f"<video src='{block.url}' controls></video>",
    # RichBlockMap: lambda block: f"<a href='https://maps.google.com/?q={block.latitude},{block.longitude}'>Location</a>",
    # RichBlockTable: lambda block: f"<table>{block.render()}</table>",
    # RichBlockDetails: lambda block: f"<details><summary>{block.summary}</summary>{block.render()}</details>",
    # RichBlockMathematicalExpression: lambda block: f"<math>{block.expression}</math>",
    str: lambda block, _: block,
    RichTextBold: lambda b, r: tag("strong", value=r(b.text)),
    RichTextItalic: lambda b, r: tag("em", value=r(b.text)),
    RichTextUnderline: lambda b, r: tag("ins", value=r(b.text)),
    RichTextStrikethrough: lambda b, r: tag("strike", value=r(b.text)),
    RichTextSpoiler: lambda b, r: tag("tg-spoiler", value=r(b.text)),
    # RichTextDateTime: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    # RichTextTextMention: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    # RichTextSubscript: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    # RichTextSuperscript: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    # RichTextMarked: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    # RichTextCode: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    RichTextCustomEmoji: lambda b, r: tag("tg-emoji", value=b.alternative_text, attrs={"emoji-id": b.custom_emoji_id}),
    # RichTextMathematicalExpression: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    # RichTextUrl: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    # RichTextEmailAddress: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    # RichTextPhoneNumber: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    # RichTextBankCardNumber: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    # RichTextMention: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    # RichTextHashtag: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    # RichTextCashtag: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    # RichTextBotCommand: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    RichTextAnchor: lambda b, r: tag("a", attrs={"name": b.name}),
    RichTextAnchorLink: lambda b, r: tag(
        "a", value=r(b.text), attrs={"href": f"#{b.anchor_name}"}
    ),
    # RichTextReference: lambda b, r: tag("span", value=f"{type(b).__name__}"),
    # RichTextReferenceLink: lambda b, r: tag("span", value=f"{type(b).__name__}"),
}


def main():
    text = render(BLOCKS, HTML_MAPPER)
    print(text)


if __name__ == "__main__":
    main()
