from typing import Union

from .input_profile_photo_animated import InputProfilePhotoAnimated
from .input_profile_photo_static import InputProfilePhotoStatic

InputProfilePhotoUnion = Union[InputProfilePhotoStatic, InputProfilePhotoAnimated]
