name: Label new pull request

on:
  pull_request_target:
    types:
      - opened
    branches:
      - dev-2.x

jobs:
  put-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add 2.x label
        uses: andymckay/labeler@master
        with:
          add-labels: 2.x
