name: "Check that changes are described"
on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "labeled"
      - "unlabeled"

permissions:
  contents: read

jobs:
  changes-required:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'skip news')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install towncrier
        run: pip install -U towncrier

      - name: Check changelog
        id: towncrier
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        run: |
          git fetch --no-tags origin +refs/heads/${BASE_BRANCH}:refs/remotes/origin/${BASE_BRANCH}
          towncrier check --compare-with origin/${BASE_BRANCH}

      - name: Save check result
        if: "always()"
        env:
          CHECK_OUTCOME: ${{ steps.towncrier.outcome }}
        run: echo "${CHECK_OUTCOME}" > "${RUNNER_TEMP}/changelog-state.txt"

      - name: Upload check result
        if: "always()"
        uses: actions/upload-artifact@v4
        with:
          name: changelog-check
          path: ${{ runner.temp }}/changelog-state.txt

  skip-news:
    runs-on: ubuntu-latest
    if: "contains(github.event.pull_request.labels.*.name, 'skip news')"
    steps:
      - name: Save check result
        run: echo "skip-news" > "${RUNNER_TEMP}/changelog-state.txt"

      - name: Upload check result
        uses: actions/upload-artifact@v4
        with:
          name: changelog-check
          path: ${{ runner.temp }}/changelog-state.txt
